#!/bin/sh


files='zshrc vimrc vim dircolors tmux.conf'

cd
for i in $files; do
	rm -r ~/.$i
	ln -s ~/.dotfiles/$i ~/.$i
done


#add keyboard layout if possible
#sudo ~/.dotfiles/KeyboardLayout/push own



## ZSH files
#file="zshrc"
#rm ~/.$file
#cp $file ~/.$file

## TMUX files
#file="tmux.conf"
#rm ~/.$file
#cp $file ~/.$file


