#!/bin/sh


files='zshrc tmux-conf vimrc vim dircolors'

for i in $files; do
	ln -s ~/.dotfiles/$i ~/.$i
done


#add keyboard layout if possible
cd ~/.dotfiles/KeyboardLayout
sudo ./push own



## ZSH files
#file="zshrc"
#rm ~/.$file
#cp $file ~/.$file

## TMUX files
#file="tmux.conf"
#rm ~/.$file
#cp $file ~/.$file


